
import com.sun.glass.events.KeyEvent;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.util.Date;
import java.util.Random;
import java.util.Scanner;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dilpreet
 */
public class aStudentAdmission1 extends javax.swing.JFrame {

    
     private static Pattern DATE_PATTERN = Pattern.compile( "^\\d{2}-\\d{2}-\\d{4}$");
     
     
     
    /**
     * Creates new form aStudentAdmission1
     */
     final static int IMG_WIDTH=100;
    final static int IMG_HEIGHT=100;
    String x="",photo="";
    JFileChooser jFileChooser1=new JFileChooser();
    
    public aStudentAdmission1() {
        initComponents();
    }
    clscon objcon=new clscon();
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ssem = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        srn = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        sdob = new javax.swing.JTextField();
        sfn = new javax.swing.JTextField();
        smn = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        sphoto = new javax.swing.JLabel();
        scls = new javax.swing.JComboBox<>();
        sdoa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nnotification = new javax.swing.JLabel();
        dobnotification = new javax.swing.JLabel();
        fnnotification = new javax.swing.JLabel();
        mnnotification = new javax.swing.JLabel();
        rroll = new javax.swing.JLabel();
        clsnotification = new javax.swing.JLabel();
        semnotification = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        semail = new javax.swing.JTextField();
        spn = new javax.swing.JTextField();
        em = new javax.swing.JLabel();
        epn = new javax.swing.JLabel();
        pnotification = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Address = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Father Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Mother Name");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Class");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Admission mode");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Date of Admission");

        ssem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+2", "Lateral Entry" }));
        ssem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ssemItemStateChanged(evt);
            }
        });

        jButton3.setText("Upload Photo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        sname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                snameKeyTyped(evt);
            }
        });

        sdob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sdobFocusLost(evt);
            }
        });
        sdob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sdobKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sdobKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sdobKeyTyped(evt);
            }
        });

        sfn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfnActionPerformed(evt);
            }
        });
        sfn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sfnKeyTyped(evt);
            }
        });

        smn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                smnKeyTyped(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        sphoto.setPreferredSize(new java.awt.Dimension(180, 180));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sphoto, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sphoto, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        );

        scls.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select a Class" }));
        scls.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sclsItemStateChanged(evt);
            }
        });

        sdoa.setText("jLabel13");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("    Student Registration");

        rroll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rroll.setText("Roll No");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Data of Birth");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Name");

        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("dd-mm-yyyy");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("E-mail");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Phone Number");

        semail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                semailFocusLost(evt);
            }
        });
        semail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semailActionPerformed(evt);
            }
        });
        semail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                semailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                semailKeyTyped(evt);
            }
        });

        spn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                spnFocusLost(evt);
            }
        });
        spn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spnActionPerformed(evt);
            }
        });
        spn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spnKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Address");

        Address.setColumns(20);
        Address.setRows(5);
        jScrollPane1.setViewportView(Address);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(74, 74, 74))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(52, 52, 52)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ssem, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dobnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fnnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sfn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(smn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mnnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(srn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sdob, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(clsnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(scls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(semnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sdoa, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(semail, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(em, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(epn, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton1)
                                            .addGap(123, 123, 123)
                                            .addComponent(jButton2))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(spn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(37, 37, 37)
                                            .addComponent(pnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(rroll, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scls, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rroll, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(srn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nnotification)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dobnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fnnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(sfn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(mnnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(smn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(clsnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(semnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(ssem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(sdoa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(semail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(em, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(epn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(spn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(35, 35, 35))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private static BufferedImage resizeImage(BufferedImage originalImage, int type){
		BufferedImage resizedImage = new BufferedImage(IMG_WIDTH, IMG_HEIGHT, type);
		Graphics2D g = resizedImage.createGraphics();
		g.drawImage(originalImage, 0, 0, IMG_WIDTH, IMG_HEIGHT, null);
		g.dispose();
	return resizedImage;
}

    private void ssemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ssemItemStateChanged

       /* try{
            String qry="select * from addclass where class_name='"+scls.getSelectedItem().toString()+"' && semester ='"+ssem.getSelectedItem().toString()+"'";
            ResultSet rs=objcon.connection2(qry);
            while(rs.next()){
                sfee.setText(rs.getString(4).toString());
            }

        }catch(Exception e){
            System.out.println(e.getMessage());

        }*/

    }//GEN-LAST:event_ssemItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        

        try{
            
        int y=jFileChooser1.showOpenDialog(this);
        x=jFileChooser1.getSelectedFile().getAbsolutePath();
            System.out.println(x);

        String nm=jFileChooser1.getSelectedFile().getName();
            int l=nm.length();
            int l1=l-4;
            String x1=nm.substring(l1,l);
            String x2=nm.substring(0,l1);
            System.out.println(x);
            if(x1.equals(".jpg") || x1.equals(".JPG"))
            {
                
            
        BufferedImage originalImage = ImageIO.read(new File(x));
            int type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();

        
            BufferedImage resizeImageJpg = resizeImage(originalImage, type);
    
                
                Random rd=new Random();
                int r=rd.nextInt(1000);
                ImageIO.write(resizeImageJpg, "jpg", new File("student\\"+x2+r+x1)); 
                    System.out.println("done");
                    sphoto.setText("");
                    sphoto.setSize(182,151);
                    photo=x2+r+x1;
                    sphoto.setIcon(new ImageIcon("student\\"+x2+r+x1));
                    }else{
                        JOptionPane.showMessageDialog(null,"PLEASE SELECT .JPG FORMAT");
                    }
                }catch(IOException e){
                    System.out.println(e.getMessage());
                }

                

    }//GEN-LAST:event_jButton3ActionPerformed

    private void snameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snameKeyTyped
        // TODO add your handling code here:

        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||(c==KeyEvent.VK_SPACE) ||(c==KeyEvent.VK_BACKSPACE) ))
        {
            evt.consume();
            nnotification.setText("*Enter only Characters");

        }
        else
        {
            nnotification.setText("");
        }
    }//GEN-LAST:event_snameKeyTyped

    private void sfnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sfnKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||(c==KeyEvent.VK_SPACE) ||(c==KeyEvent.VK_BACKSPACE) ))
        {
            evt.consume();
            fnnotification.setText("*Enter only Charactes");

        }
        else
        {
            fnnotification.setText("");
        }
    }//GEN-LAST:event_sfnKeyTyped

    private void smnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_smnKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||(c==KeyEvent.VK_SPACE) ||(c==KeyEvent.VK_BACKSPACE) ))
        {
            evt.consume();
            mnnotification.setText("*Enter ony Characters");

        }
        else
        {
            mnnotification.setText("");
        }
    }//GEN-LAST:event_smnKeyTyped

    private void sclsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sclsItemStateChanged
       /* try{
            
            ssem.removeAllItems();
            String qry="select * from addclass where class_name='"+scls.getSelectedItem().toString()+"'";
            ResultSet rs=objcon.connection2(qry);
            while(rs.next()){
                ssem.addItem(rs.getString(3).toString());
                jLabel12.setText("You can choose semester from here");
            }

        }catch(Exception e){
            System.out.println(e.getMessage());

        }*/

    }//GEN-LAST:event_sclsItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        
         try{
                String qry="select  distinct class_name from addclass";
                ResultSet rs=objcon.connection2(qry);
                while(rs.next()){
                      scls.addItem(rs.getString(1).toString());
                }
                
                
                
                String roll="";
                qry="";
                qry="select  * from tbstudentadmission ORDER BY id ASC";
                ResultSet rs1=objcon.connection2(qry);
                
                int a=0;
                
                
                while(rs1.next() && rs!=null){
                   a++;
                     roll=rs1.getString(1).toString();
                     
                      System.out.println(roll);
                }
            
                
                
                
                if(roll.equals("")){
                    srn.setText("1");
                }else{
                        int y=Integer.parseInt(roll);
                        y++;
                        srn.setText(""+y);
                }
                
                
                
            }catch(Exception e){
                System.out.println(e.getMessage());
            
            }
          Date d=new Date();
            SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
        
        String Dtnw=sdf.format(d);
        sdoa.setText(""+Dtnw);
        
         
         
         
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        
        if (!(Pattern.matches("^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$", semail.getText()))) 
                {
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
            em.setText("*Please enter a valid email");
            semail.setText("");

            }
            else
            {
                em.setText("");
            }
        
        
        
        
        
        
        
          
        try {
            
        
        if(DATE_PATTERN.matcher(sdob.getText().toString()).matches())
        {
                
            int dt=Integer.parseInt(sdob.getText().toString().substring(0,2));
            int mn=Integer.parseInt(sdob.getText().toString().substring(3,5));
            int yr=Integer.parseInt(sdob.getText().toString().substring(6,10));
            
            
            System.out.println(dt+"---"+mn+"---"+yr);
            
            
            LocalDate endofCentury = LocalDate.of(yr,mn,dt);
LocalDate now = LocalDate.now();
 
Period diff = Period.between(endofCentury, now);
 System.out.println(dt+"---"+mn+"---"+yr);
            
System.out.printf("Difference is %d years, %d months and %d days old",
                    diff.getYears(), diff.getMonths(), diff.getDays());
                      if(diff.getYears()>=17){
                          
                      }else{
                          JOptionPane.showMessageDialog(null, "Your are not within age limit");
                          sdob.setText("");
                      }  


        }
        else
        {
         JOptionPane.showMessageDialog(null, "Please enter correct date like dd-mm-yyyy");
         sdob.setText("");
        }
        }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"Please enter proper Data within date bounds");
             sdob.setText("");
        }
       
        
        
        
        
        // TODO add your handling code here:
        
      
        int l=spn.getText().length();
        if(scls.getSelectedItem().equals("Please Select a Class"))
        {
        semnotification.setText("Please choose a class");
        }
        
        if(!sname.getText().equals("") && !sdob.getText().equals("") && !sfn.getText().equals("") && !smn.getText().equals("") && !scls.getSelectedItem().toString().equals("") && !ssem.getSelectedItem().toString().equals("") && !photo.equals("") && !semail.getText().equals("") && !spn.getText().equals("") &&(l==10)  && !semail.getText().equals(Pattern.compile( "^\\d{2}-\\d{2}-\\d{4}$")) && !scls.getSelectedItem().equals("Please Select a Class"))
        {
             try {
                 String qry="";
              /*String roll="";
              
               String qry="select  * from tbstudentadmission";
                ResultSet rs1=objcon.connection2(qry);
                while(rs1.next()){
                      roll=rs1.getString(1).toString();
                      System.out.println(roll);
                }
                
                
                
                
                if(roll.equals("")){
                    srn.setText("1");
                }else{
                        int y=Integer.parseInt(roll);
                        y++;
                        srn.setText(""+y);
                        rroll.setText("Roll no");
                        
                }
                */
              JOptionPane.showMessageDialog(null, "Student roll no is"+srn.getText().toString());
                clscon obj=new clscon();
                qry="";
                qry="select * from tbstudentadmission where  email='"+semail.getText()+"'";
                ResultSet rs2=obj.connection2(qry);
                int z=0;
                while(rs2.next())
                {
                    z++;
                }
                qry="";
               qry="select * from tbstudentadmission where photo ='"+photo+"'";
               ResultSet rss=obj.connection2(qry);
               int rss1=0;
               while(rss.next())
               {
                   rss1++;
               }
                
                qry="";
                qry="select * from tbstudentadmission where  phone='"+spn.getText()+"'";
                ResultSet rs3=obj.connection2(qry);
                int z1=0;
                while(rs3.next() && rs3!=null)
                {
                    z1++;
                }
                if(z>0)
                {
                    JOptionPane.showMessageDialog(null, "This email is already registered");
                    semail.setText("");
                    
                }
                
                if(z1>0)
                {
                    JOptionPane.showMessageDialog(null, "This mobile number already registered");
                    spn.setText("");
                }
                
                
                
                
                
                
                
                
                
                
                
                
          
            
            
           
                
                
            
            
            
                
            
                
             
            
            
            
            
            
            
            
      if(z==0 && z1==0 && rss1==0 && !semail.getText().equals("") && !spn.getText().equals("") && !Address.getText().toString().equals(""))
      {      
            
  clscon obj1=new clscon();
  qry="";
  qry="insert into tbstudentadmission (rollno,name,dob,fn,mn,class,m_o_a,doa,photo,email,phone,address) values ('"+srn.getText().toString()+"','"+sname.getText().toString()+"','"+sdob.getText().toString()+"','"+sfn.getText().toString()+"','"+smn.getText().toString()+"','"+scls.getSelectedItem().toString()+"','"+ssem.getSelectedItem().toString()+"','"+sdoa.getText().toString()+"','"+photo+"','"+semail.getText().toString()+"','"+spn.getText().toString()+"','"+Address.getText().toString()+"')";
  obj1.connection(qry);
 
  JOptionPane.showMessageDialog(null, "Data Successfully inserted","Data inserted",JOptionPane.INFORMATION_MESSAGE);
  semail.setText("");
  spn.setText("");
  
  
  int y1=Integer.parseInt(srn.getText().toString())+1;
  srn.setText(""+y1);
  
  
      }
      else
      {
          JOptionPane.showMessageDialog(null, "Something went wrong");
      }
      
     
  
  
  
        
        } catch (Exception e) {
                 System.out.println(e.getMessage());
        }
  
       
               
        
        
        
        
       
               
        }  
        else
        {
            JOptionPane.showMessageDialog(null, "please fill all the entries");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sfnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sfnActionPerformed

    private void sdobKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sdobKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_sdobKeyReleased

    private void sdobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sdobKeyTyped
        
        
    }//GEN-LAST:event_sdobKeyTyped

    private void sdobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sdobKeyPressed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_sdobKeyPressed

    private void sdobFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sdobFocusLost
        
        try {
            
        
        if(DATE_PATTERN.matcher(sdob.getText().toString()).matches())
        {
                
            int dt=Integer.parseInt(sdob.getText().toString().substring(0,2));
            int mn=Integer.parseInt(sdob.getText().toString().substring(3,5));
            int yr=Integer.parseInt(sdob.getText().toString().substring(6,10));
            
            
            System.out.println(dt+"---"+mn+"---"+yr);
            
            
            LocalDate endofCentury = LocalDate.of(yr,mn,dt);
LocalDate now = LocalDate.now();
 
Period diff = Period.between(endofCentury, now);
 System.out.println(dt+"---"+mn+"---"+yr);
            
System.out.printf("Difference is %d years, %d months and %d days old",
                    diff.getYears(), diff.getMonths(), diff.getDays());
                      if(diff.getYears()>=17){
                          
                      }else{
                          JOptionPane.showMessageDialog(null, "Your are not within age limit");
                          sdob.setText("");
                      }  


        }
        else
        {
         JOptionPane.showMessageDialog(null, "Please enter correct date like dd-mm-yyyy");
         sdob.setText("");
        }
        }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"Please enter proper Data within date bounds");
             sdob.setText("");
        }
       
    }//GEN-LAST:event_sdobFocusLost

    private void semailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_semailKeyTyped
        // TODO add your handling code here:
      
        
        
    }//GEN-LAST:event_semailKeyTyped

    private void semailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_semailKeyReleased
        // TODO add your handling code here:
         
    }//GEN-LAST:event_semailKeyReleased

    private void semailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_semailFocusLost
        // TODO add your handling code here:
          if (!(Pattern.matches("^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$", semail.getText()))) 
                {
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
            em.setText("*Please enter a valid email");
            semail.setText("");

            }
            else
            {
                em.setText("");
            }
    }//GEN-LAST:event_semailFocusLost

    private void semailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semailActionPerformed

    private void spnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spnActionPerformed

    private void spnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spnFocusLost
        // TODO add your handling code here:
        
       int l=spn.getText().length();
      if(l==10)
      {
         epn.setText("");
      }
      else
      {
          epn.setText(" Please Enter 10 Digit mobile number");
      }
          
    }//GEN-LAST:event_spnFocusLost

    private void spnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if((Character.isAlphabetic(c) ||(c==KeyEvent.VK_SPACE) ||(c==KeyEvent.VK_BACKSPACE) ))
        {
            evt.consume();
          pnotification.setText("*Enter only Integers");

        }
        else
        {
            pnotification.setText("");
        }
    }//GEN-LAST:event_spnKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aStudentAdmission1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aStudentAdmission1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aStudentAdmission1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aStudentAdmission1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aStudentAdmission1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Address;
    private javax.swing.JLabel clsnotification;
    private javax.swing.JLabel dobnotification;
    private javax.swing.JLabel em;
    private javax.swing.JLabel epn;
    private javax.swing.JLabel fnnotification;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mnnotification;
    private javax.swing.JLabel nnotification;
    private javax.swing.JLabel pnotification;
    private javax.swing.JLabel rroll;
    private javax.swing.JComboBox<String> scls;
    private javax.swing.JLabel sdoa;
    private javax.swing.JTextField sdob;
    private javax.swing.JTextField semail;
    private javax.swing.JLabel semnotification;
    private javax.swing.JTextField sfn;
    private javax.swing.JTextField smn;
    private javax.swing.JTextField sname;
    private javax.swing.JLabel sphoto;
    private javax.swing.JTextField spn;
    private javax.swing.JLabel srn;
    private javax.swing.JComboBox<String> ssem;
    // End of variables declaration//GEN-END:variables
}
