
import com.sun.glass.events.KeyEvent;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.util.Date;
import java.util.Random;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dilpreet
 */
public class aTeacherAdmission extends javax.swing.JFrame {
     
     private static Pattern DATE_PATTERN = Pattern.compile( "^\\d{2}-\\d{2}-\\d{4}$");

    /**
     * Creates new form aTeacherAdmission
     */
     clscon obj=new clscon();
      final static int IMG_WIDTH=100;
    final static int IMG_HEIGHT=100;
    String x="",photo="";
    JFileChooser jFileChooser1=new JFileChooser();
    public aTeacherAdmission() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private static BufferedImage resizeImage(BufferedImage originalImage, int type){
		BufferedImage resizedImage = new BufferedImage(IMG_WIDTH, IMG_HEIGHT, type);
		Graphics2D g = resizedImage.createGraphics();
		g.drawImage(originalImage, 0, 0, IMG_WIDTH, IMG_HEIGHT, null);
		g.dispose();
	return resizedImage;
}

    
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sphoto1 = new javax.swing.JLabel();
        reg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        edob = new javax.swing.JTextField();
        nme = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        pn = new javax.swing.JTextField();
        cat = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        sphoto = new javax.swing.JLabel();
        qul = new javax.swing.JComboBox<>();
        dom = new javax.swing.JComboBox<>();
        lblId = new javax.swing.JLabel();
        nnotifiaction = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fnnotification = new javax.swing.JLabel();
        emnotification = new javax.swing.JLabel();
        pnnotification = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dobnotification = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        des = new javax.swing.JComboBox<>();
        pnnotofication1 = new javax.swing.JLabel();
        rn = new javax.swing.JLabel();
        doa = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        sphoto1.setPreferredSize(new java.awt.Dimension(180, 180));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        reg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reg.setText("Registration No");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Data of Birth");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Father Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Domicile");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Qualification");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Category");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Date of Aplication");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("E-mail");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Phone Number");

        edob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edobFocusLost(evt);
            }
        });

        nme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmeActionPerformed(evt);
            }
        });
        nme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nmeKeyTyped(evt);
            }
        });

        fn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnKeyTyped(evt);
            }
        });

        mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailFocusLost(evt);
            }
        });

        pn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pnKeyTyped(evt);
            }
        });

        cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gen", "OC", "SC" }));

        jButton3.setText("Upload Photo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sphoto, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sphoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        );

        qul.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                qulItemStateChanged(evt);
            }
        });
        qul.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                qulFocusLost(evt);
            }
        });

        dom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Punjab", "Other state" }));

        jLabel3.setText("dd-mm-yyyy");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Salary");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Designation");

        des.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                desItemStateChanged(evt);
            }
        });
        des.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                desFocusLost(evt);
            }
        });

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(88, 88, 88)
                        .addComponent(doa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(129, 129, 129)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(nme, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(nnotifiaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(123, 123, 123))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14))
                                        .addGap(102, 102, 102)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(pnnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(dom, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(mail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addComponent(emnotification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(qul, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(375, 375, 375))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(fn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(fnnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pnnotofication1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton1)
                                        .addGap(133, 133, 133)
                                        .addComponent(jButton2)
                                        .addGap(118, 118, 118)
                                        .addComponent(jButton4)
                                        .addGap(16, 16, 16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(117, 117, 117)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(dobnotification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(edob, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(reg, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(71, 71, 71)
                                                .addComponent(rn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(142, 142, 142)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(reg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblId)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nnotifiaction, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dobnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fnnotification, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(dom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(qul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(doa, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnnotofication1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton4))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        
        
        
        try{
            
        int y=jFileChooser1.showOpenDialog(this);
        x=jFileChooser1.getSelectedFile().getAbsolutePath();
       System.out.println("2sttt-----"+x);

        String nm=jFileChooser1.getSelectedFile().getName();
            int l=nm.length();
            int l1=l-4;
            String x1=nm.substring(l1,l);
            String x2=nm.substring(0,l1);
            System.out.println("3sttt-----"+x);
            if(x1.equals(".jpg") || x1.equals(".JPG"))
            {
                
            
        BufferedImage originalImage = ImageIO.read(new File(x));
            int type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();

        
            BufferedImage resizeImageJpg = resizeImage(originalImage, type);
    
                
                Random rd=new Random();
                int r=rd.nextInt(1000);
                ImageIO.write(resizeImageJpg, "jpg", new File("teacher\\"+x2+r+x1)); 
                    System.out.println("done");
                    sphoto.setText("");
                    sphoto.setSize(182,151);
                    photo=x2+r+x1;
                    sphoto.setIcon(new ImageIcon("teacher\\"+x2+r+x1));
                    System.out.println("done");
                    //System.out.println("done");
                    
                    }else{
                        JOptionPane.showMessageDialog(null,"PLEASE SELECT .JPG FORMAT");
                    }
                }catch(IOException e){
                    System.out.println(e.getMessage());
                }

                


    }//GEN-LAST:event_jButton3ActionPerformed

    private void nmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmeActionPerformed

    private void nmeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nmeKeyTyped
        // TODO add your handling code here:
        
        
         char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||(c==KeyEvent.VK_SPACE) ||(c==KeyEvent.VK_BACKSPACE) ))
        {
            evt.consume();
            nnotifiaction.setText("*Enter only Characters");

        }
        else
        {
            nnotifiaction.setText("");
        }
    }//GEN-LAST:event_nmeKeyTyped

    private void edobFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edobFocusLost
        // TODO add your handling code here:
        
        
        
        
        
        try {
            
        
        if(DATE_PATTERN.matcher(edob.getText().toString()).matches())
        {
                
            int dt=Integer.parseInt(edob.getText().toString().substring(0,2));
            int mn=Integer.parseInt(edob.getText().toString().substring(3,5));
            int yr=Integer.parseInt(edob.getText().toString().substring(6,10));
            
            
            System.out.println(dt+"---"+mn+"---"+yr);
            
            
            LocalDate endofCentury = LocalDate.of(yr,mn,dt);
LocalDate now = LocalDate.now();
 
Period diff = Period.between(endofCentury, now);
 System.out.println(dt+"---"+mn+"---"+yr);
            
System.out.printf("Difference is %d years, %d months and %d days old",
                    diff.getYears(), diff.getMonths(), diff.getDays());
                      if(diff.getYears()>=17){
                          
                      }else{
                          JOptionPane.showMessageDialog(null, "Your are not within age limit");
                          edob.setText("");
                      }  


        }
        else
        {
         JOptionPane.showMessageDialog(null, "Please enter correct date like dd-mm-yyyy");
         edob.setText("");
        }
        }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"Please enter proper Data within date bounds");
             edob.setText("");
        }
       
    }//GEN-LAST:event_edobFocusLost

    private void fnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnKeyTyped
        // TODO add your handling code here:
        
        
            char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||(c==KeyEvent.VK_SPACE) ||(c==KeyEvent.VK_BACKSPACE) ))
        {
            evt.consume();
            fnnotification.setText("*Enter only Characters");

        }
        else
        {
            fnnotification.setText("");
        }
    }//GEN-LAST:event_fnKeyTyped

    private void mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusLost
        // TODO add your handling code here:
        
        
         if (!(Pattern.matches("^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$", mail.getText()))) 
                {
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
            emnotification.setText("*Please enter a valid email");
            emnotification.setText("");

            }
            else
            {
                emnotification.setText("");
            }
    }//GEN-LAST:event_mailFocusLost

    private void pnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if((Character.isAlphabetic(c) ||(c==KeyEvent.VK_SPACE) ||(c==KeyEvent.VK_BACKSPACE) ))
        {
            evt.consume();
            pnnotification.setText("*Enter only Characters");

        }
        else
        {
            nnotifiaction.setText("");
        }
        
        
    }//GEN-LAST:event_pnKeyTyped

    private void qulItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_qulItemStateChanged
        // TODO add your handling code here:
        
         if(qul.getSelectedItem().equals("Ph.D"))
        {
            des.removeAllItems();
            des.addItem("Lecturar");

            des.addItem("Assistant Lecturar");
            des.addItem("Librarian");
            des.addItem("Lab Attented");
            des.addItem("Peon");
        }
        if(qul.getSelectedItem().equals("M.TECH"))
        {
            des.removeAllItems();
            des.removeItem("Lecturar");
            des.addItem("Assistant Lecturar");
            des.addItem("Librarian");
            des.addItem("Lab Attented");
            des.addItem("Peon");
        }
        if(qul.getSelectedItem().equals("GRADUATION"))
        {
            des.removeAllItems();
            des.removeItem("Lecturar");

            des.removeItem("Assistant Lecturar");
            des.addItem("Librarian");
            des.addItem("Lab Attented");
            des.addItem("Peon");
        }
        if(qul.getSelectedItem().equals("DIPLOMA"))
        {
            des.removeAllItems();
            des.removeItem("Lecturar");

            des.removeItem("Assistant Lecturar");
            des.addItem("Librarian");
            des.addItem("Lab Attented");
            des.addItem("Peon");
        }
      
         
        
    }//GEN-LAST:event_qulItemStateChanged
public void getId(){
    try{
        int id=0;
        String qry="select * from tbstaff";
        ResultSet rs=obj.connection2(qry);
        while(rs.next()){
            id=Integer.parseInt(rs.getString("id"));
        }
        //id++;
        
        lblId.setText(""+id);
    }catch(Exception e){
        System.out.println(e.getMessage());
    }
}
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

   Date d=new Date();
            SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
        
        String Dtnw=sdf.format(d);
        doa.setText(""+Dtnw);

// TODO add your handling code here:

        
        
        try 
        {
            
            String qry="select distinct qualification from addsalary";
            ResultSet rs=obj.connection2(qry);
            while(rs.next())
            {
                String qualification=rs.getString("qualification");
                qul.addItem(qualification);
            }
            
        } 
        catch (Exception e) 
        {
            System.out.println(e.getMessage());
        }
        
        
        
         String empid="";
              
               String qry="select  * from tbstaff ORDER BY id ASC";
                ResultSet rs1=obj.connection2(qry);
                
                int a=0;
                
                
              try {
                    while(rs1.next() && rs1!=null)
                    {
                   a++;
                     empid=rs1.getString(1).toString();
                     
                      System.out.println(empid);
                    }
            
                
                
                
                if(empid.equals("")){
                    rn.setText("1");
                }else{
                        int y=Integer.parseInt(empid);
                        y++;
                        rn.setText(""+y);
                }
                
            
        } catch (Exception e) 
        {
            System.out.println(e.getMessage());
        }
        
        
        
       
     
        
    }//GEN-LAST:event_formWindowOpened

    private void desItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_desItemStateChanged
        // TODO add your handling code here:
        
        try 
        {
            clscon obj=new clscon();
            String qry="select * from addsalary where qualification ='"+qul.getSelectedItem().toString()+"' && designation ='"+des.getSelectedItem().toString()+"'";
            ResultSet rs=obj.connection2(qry);
            while(rs.next())
            {
                sal.setText(rs.getString(4).toString());
            }
        } 
        catch (Exception e)
        {
            System.out.println(e.getMessage());
        }
        
        
       
         
    }//GEN-LAST:event_desItemStateChanged

    private void qulFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qulFocusLost

        
       
    }//GEN-LAST:event_qulFocusLost

    private void desFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_desFocusLost
            
        
        
        
    }//GEN-LAST:event_desFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

if (!(Pattern.matches("^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$", mail.getText()))) 
                {
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
            emnotification.setText("*Please enter a valid email");
            emnotification.setText("");

            }
            else
            {
                emnotification.setText("");
            }

        // TODO add your handling code here:
        
        try {
            
       
       clscon obj=new clscon();
        String qry="select * from tbstaff where email='"+mail.getText().toString()+"' && phone='"+pn.getText().toString()+"'";
        ResultSet rs=obj.connection2(qry);
        int a=0;
        while(rs.next())
        {
            a++;
        }
        if(a>0)
        {
            emnotification.setText("This email is already registered");
            pnnotification.setText("This phone number is already registered");
        }
        else
        {
             emnotification.setText("");
            pnnotification.setText("");
        }
        if(a==0){
            if(pn.getText().length()==10)
            {
        
        if(!nme.getText().equals("") && !edob.getText().equals("") && !fn.getText().equals("") && !dom.getSelectedItem().toString().equals("") && !qul.getSelectedItem().toString().equals("") && !des.getSelectedItem().toString().equals("") && !mail.getText().equals("") && !pn.getText().equals("") && !photo.equals(""))
        {
          qry="";
           qry="insert into tbstaff (name,dob,fn,domicile,qualification,desig,salary,category,doa,email,phone,photo,emp_id) values ('"+nme.getText().toString()+"','"+edob.getText().toString()+"','"+fn.getText().toString()+"','"+dom.getSelectedItem().toString()+"','"+qul.getSelectedItem().toString()+"','"+des.getSelectedItem().toString()+"','"+sal.getText().toString()+"','"+cat.getSelectedItem().toString()+"','"+doa.getText().toString()+"','"+mail.getText().toString()+"','"+pn.getText().toString()+"','"+photo.toString()+"','"+rn.getText().toString()+"')";
            obj.connection(qry);
            getId();
            
                    

            //reg.setText("Registration No");
            JOptionPane.showMessageDialog(null, "Employee No"+ lblId.getText());
            
            frmAsignup obj1=new frmAsignup();
            obj1.setVisible(true);
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select all the fields");
        }
        }
            else
            {
               pnnotofication1.setText("please enter 10 digit mobile no");
            }
        }
        }
        catch (Exception e) 
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aTeacherAdmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aTeacherAdmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aTeacherAdmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aTeacherAdmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aTeacherAdmission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cat;
    private javax.swing.JComboBox<String> des;
    private javax.swing.JLabel doa;
    private javax.swing.JLabel dobnotification;
    private javax.swing.JComboBox<String> dom;
    private javax.swing.JTextField edob;
    private javax.swing.JLabel emnotification;
    private javax.swing.JTextField fn;
    private javax.swing.JLabel fnnotification;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField nme;
    private javax.swing.JLabel nnotifiaction;
    private javax.swing.JTextField pn;
    private javax.swing.JLabel pnnotification;
    private javax.swing.JLabel pnnotofication1;
    private javax.swing.JComboBox<String> qul;
    private javax.swing.JLabel reg;
    private javax.swing.JLabel rn;
    private javax.swing.JLabel sal;
    private javax.swing.JLabel sphoto;
    private javax.swing.JLabel sphoto1;
    // End of variables declaration//GEN-END:variables
}
