
import com.sun.glass.events.KeyEvent;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.Period;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.text.*;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dilpreet
 */
public class getfeefromstudent extends javax.swing.JFrame {
        private static Pattern DATE_PATTERN = Pattern.compile( "^\\d{2}-\\d{2}-\\d{4}$");
    /**
     * Creates new form getfeefromstudent
     */
        int x=0;
        String photo1;
    clscon obj=new clscon();
    public getfeefromstudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rollno = new javax.swing.JTextField();
        semm = new javax.swing.JComboBox<>();
        name = new javax.swing.JLabel();
        fathername = new javax.swing.JLabel();
        fee = new javax.swing.JLabel();
        dte = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rollnotification = new javax.swing.JLabel();
        clss = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        photo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Roll No");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Class");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Semester");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Name");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Father Name");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Fee");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Date");

        rollno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rollnoFocusLost(evt);
            }
        });
        rollno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rollnoKeyTyped(evt);
            }
        });

        semm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Choose a Semester" }));
        semm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                semmItemStateChanged(evt);
            }
        });
        semm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                semmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                semmFocusLost(evt);
            }
        });
        semm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                semmMouseClicked(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        clss.setText("jLabel1");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(photo, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fathername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(clss, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(dte, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rollno, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addComponent(rollnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(semm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton1)
                        .addGap(101, 101, 101)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rollno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rollnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(clss))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(semm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(fathername, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addComponent(dte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
 
        
        
        
       try
        {
             String qry="select distinct semester from addclass";
        ResultSet rs=obj.connection2(qry);
            while(rs.next())
                    {
                        semm.addItem(rs.getString(1));
                        
                    }
            
        }
        catch (Exception e) 
        {
            System.out.println(e.getMessage());
        }
              
     
    
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void semmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_semmItemStateChanged
if(!rollno.getText().equals("")){
          name.setVisible(true);
fathername.setVisible(true);
}
    
    
  
        int y=0;     
        try 
        {
         String qry="select * from addclass  where class_name='"+clss.getText().toString()+"' && semester ='"+semm.getSelectedItem().toString()+"'";
         ResultSet rs= obj.connection2(qry);
           
         while(rs.next())
       {
           y++;
          // name.setText(rs.getString(3));
           //fathername.setText(rs.getString(5));
           //fee.setText(rs.getString(9));
          fee.setText(rs.getString(4));
                     jButton1.setVisible(true);
      }    
         if(y==0){
             name.setText("");
             fathername.setText("");
           fee.setText("");
           dte.setText("");
         }else{
       
        Date d=new Date();
            SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
        
        String Dtnw=sdf.format(d);
        dte.setText(""+Dtnw);
         
        }
        }
        catch (Exception e)
        {
            System.out.println(e.getMessage());
        }
       
        
        
        
    }//GEN-LAST:event_semmItemStateChanged

    private void rollnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollnoKeyTyped
  char c=evt.getKeyChar();
        if((Character.isAlphabetic(c) ||(c==KeyEvent.VK_SPACE) ||(c==KeyEvent.VK_BACKSPACE) ))
        {
            evt.consume();
            rollnotification.setText("*Enter only Digits");

        }
        else
        {
            rollnotification.setText("");
        }
      
    }//GEN-LAST:event_rollnoKeyTyped

    public void getdiff(){
        String feedt="";

        String qry="select rollno,class,semester,date from studentfee where rollno='"+rollno.getText().toString()+"' && class='"+clss.getText().toString()+"'";
        try 
        {
            ResultSet rs =obj.connection2(qry);
            int a=0;
            while(rs.next())
            {
                a++;
                feedt=rs.getString(4).toString();
            }
            
            System.out.println(" check function ----  "+feedt +"------"+a);
            
        if(a==0){
            x++;
        }
            
        if(a>0)
        {
            
         
        System.out.println(" check function2 ----  "+feedt);
        
          if(DATE_PATTERN.matcher(feedt).matches())
            {
                
             
            int dt=Integer.parseInt(feedt.substring(0,2));
            int mn=Integer.parseInt(feedt.substring(3,5));
            int yr=Integer.parseInt(feedt.substring(6,10));
            
            
            System.out.println(dt+"---"+mn+"---"+yr);
            
            
            LocalDate endofCentury = LocalDate.of(yr,mn,dt);
LocalDate now = LocalDate.now();
 
Period diff = Period.between(endofCentury, now);
 System.out.println(dt+"---"+mn+"---"+yr+"dddddd");
            
System.out.printf("Difference is %d years, %d months and %d days old",
                    diff.getYears(), diff.getMonths(), diff.getDays());
               
                      if(diff.getMonths()>=4){
                         x++; 
                        
                      }else{
                          JOptionPane.showMessageDialog(null, "Fee already paid");
                 
                      }  


        }
        else
        {
         JOptionPane.showMessageDialog(null, "Please enter correct date like dd-mm-yyyy");
       
        }
        
        
        
        }
        
            
            
        } 
        catch (Exception e) 
        
        {
            System.out.println(e.getMessage());
            
        }
        
        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                   
// TODO add your handling code here:
        
        try 
        {
                    int a=0;
    String qry="";
            
          
            
               
            getdiff();
            if(x>0)
            {
                qry="";
                qry="select * from studentfee where rollno='"+rollno.getText().toString()+"' && semester='"+semm.getSelectedItem().toString()+"'";
                ResultSet rs=obj.connection2(qry);
                try 
                {
                    int z=0;
                    while(rs.next())
                    {
                      z++;  
                    }
                    if(z==0)
                    {
                        if(!rollno.getText().toString().equals("") && !clss.getText().equals("") && !semm.getSelectedItem().equals("Please Choose a Semester") && !name.getText().equals("") && !fathername.getText().equals("") && !fee.getText().equals("") && !dte.getText().equals(""))
                        {
                            qry="";
            qry="insert into studentfee(rollno,class,semester,name,fn,fee,date,pic) values('"+rollno.getText().toString()+"','"+clss.getText()+"','"+semm.getSelectedItem()+"','"+name.getText().toString()+"','"+fathername.getText().toString()+"','"+fee.getText().toString()+"','"+dte.getText().toString()+"','"+photo1+"')";
        obj.connection(qry);
            
        JOptionPane.showMessageDialog(null, "Data succesfully registered");
                    }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Please fill all the entries");
                    }
                   
                    
                }
                catch (Exception e)
                {
                    System.out.println(e.getMessage());
                    
                }
                
            
                    
            
   
        }
           
        }
        catch (Exception e)
        {
            System.out.println(e.getMessage());
        }
   
        x=0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void semmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_semmFocusLost

      







   
    }//GEN-LAST:event_semmFocusLost

    private void semmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semmMouseClicked

        // TODO add your handling code here:
        
        
        
 

    }//GEN-LAST:event_semmMouseClicked

    private void rollnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rollnoFocusLost
           Date d=new Date();
            SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
        
        String Dtnw=sdf.format(d);
        dte.setText(""+Dtnw);
        // TODO add your handling code here:
        String qry="select class,name,fn,photo from tbstudentadmission where rollno='"+rollno.getText().toString()+"'";
        ResultSet rs=obj.connection2(qry);
        try 
        {
            while(rs.next())
            {
                
                clss.setText(rs.getString(1));
                name.setText(rs.getString(2));
                fathername.setText(rs.getString(3));
                 photo.setIcon(new ImageIcon("student/"+rs.getString(4)));
               photo1="student/"+rs.getString(4);
            }
           
        }
        catch (Exception e) 
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_rollnoFocusLost

    private void semmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_semmFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_semmFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getfeefromstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(getfeefromstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(getfeefromstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(getfeefromstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new getfeefromstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clss;
    private javax.swing.JLabel dte;
    private javax.swing.JLabel fathername;
    private javax.swing.JLabel fee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel photo;
    private javax.swing.JTextField rollno;
    private javax.swing.JLabel rollnotification;
    private javax.swing.JComboBox<String> semm;
    // End of variables declaration//GEN-END:variables

  
}
